# Start from a lightweight base image
FROM alpine:latest

RUN apk update && apk add --no-cache curl jq bash unzip


COPY auto_analyze.sh /auto_analyze.sh


RUN chmod +x /auto_analyze.sh


ENTRYPOINT ["/auto_analyze.sh"]

